### ISSUE TITLE
Docker run command doesn't work

### ISSUE THREAD

**Issue by JavierArredondo** [alercebroker/ztf-api#31]
I received the following message:

```
[2021-01-27 13:48:44 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 362, in import_app
    app = eval(obj, vars(mod))
  File "<string>", line 1, in <module>
  File "/app/api/app.py", line 25, in create_app
    description = open("../description.md")
FileNotFoundError: [Errno 2] No such file or directory: '../description.md'
```
Solution: 

Change `..description.md` by `description.md` in https://github.com/alercebroker/ztf-api-new/blob/45f8674000122bbccf0d11806245acd0c38eb538/api/app.py#L25

**Comment by cvalenzu** [comment]
Fixed on 13dfcb0bf872f3c01b168c703e00fb7af87acbf0
